/*
 * Copyright (c) 2018 - Arcade Analytics LTD (https://arcadeanalytics.com)
 */

/* Generated By:JJTree: Do not edit this line. OClusterList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.arcadedb.sql.parser;

import com.arcadedb.sql.executor.Result;
import com.arcadedb.sql.executor.ResultInternal;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class BucketList extends SimpleNode {

  protected List<Identifier> buckets = new ArrayList<Identifier>();

  public BucketList(int id) {
    super(id);
  }

  public BucketList(SqlParser p, int id) {
    super(p, id);
  }

  /**
   * Accept the visitor.
   **/
  public Object jjtAccept(SqlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void toString(Map<Object, Object> params, StringBuilder builder) {

    builder.append("buckets:[");
    boolean first = true;
    for (Identifier id : buckets) {
      if (!first) {
        builder.append(",");
      }
      id.toString(params, builder);
      first = false;
    }
    builder.append("]");
  }

  public List<Bucket> toListOfClusters() {
    List<Bucket> result = new ArrayList<>();
    for (Identifier id : buckets) {
      Bucket cluster = new Bucket(-1);
      cluster.bucketName = id.getStringValue();
      result.add(cluster);
    }
    return result;
  }

  public BucketList copy() {
    BucketList result = new BucketList(-1);
    result.buckets = buckets.stream().map(x -> x.copy()).collect(Collectors.toList());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;

    BucketList that = (BucketList) o;

    if (buckets != null ? !buckets.equals(that.buckets) : that.buckets != null)
      return false;

    return true;
  }

  @Override
  public int hashCode() {
    return buckets != null ? buckets.hashCode() : 0;
  }

  public Result serialize() {
    ResultInternal result = new ResultInternal();
    if (buckets != null) {
      result.setProperty("buckets", buckets.stream().map(x -> x.serialize()).collect(Collectors.toList()));
    }
    return result;
  }

  public void deserialize(Result fromResult) {
    if (fromResult.getProperty("buckets") != null) {
      buckets = new ArrayList<>();
      List<Result> ser = fromResult.getProperty("buckets");
      for (Result item : ser) {
        Identifier id = new Identifier(-1);
        id.deserialize(item);
        buckets.add(id);
      }
    }
  }
}
/* JavaCC - OriginalChecksum=bd90ffa0b9d17f204b3cf2d47eedb409 (do not edit this line) */
