/*
 * Copyright (c) - Arcade Data LTD (https://arcadedata.com)
 */

/* Generated By:JJTree: Do not edit this line. OCreateVertexStatementNoTarget.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_USERTYPE_VISIBILITY_PUBLIC=true */
package com.arcadedb.sql.parser;

public
class CreateVertexStatementNoTarget extends CreateVertexStatement {
  public CreateVertexStatementNoTarget(int id) {
    super(id);
  }

  public CreateVertexStatementNoTarget(SqlParser p, int id) {
    super(p, id);
  }

  @Override public CreateVertexStatement copy() {
    return super.copy();
  }
}
/* JavaCC - OriginalChecksum=5213b77f14f5f89255590034bdc0ea54 (do not edit this line) */
