/*
 * Copyright (c) - Arcade Analytics LTD (https://arcadeanalytics.com)
 */

/* Generated By:JJTree: Do not edit this line. OFirstLevelExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_USERTYPE_VISIBILITY_PUBLIC=true */
package com.arcadedb.sql.parser;

public class FirstLevelExpression extends MathExpression {
  public FirstLevelExpression(int id) {
    super(id);
  }

  public FirstLevelExpression(SqlParser p, int id) {
    super(p, id);
  }

  /**
   * Accept the visitor.
   **/
  public Object jjtAccept(SqlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  @Override protected boolean supportsBasicCalculation() {
    return super.supportsBasicCalculation();
  }

  //never used, this class is never returned by the parser!
  public boolean isBaseIdentifier() {
    return value instanceof Identifier;
  }

  //never used, this class is never returned by the parser!
  @Override public MathExpression copy() {
    return super.copy();
  }
}
/* JavaCC - OriginalChecksum=30dc1016b686d4841bbd57d6e6c0bfbd (do not edit this line) */
