/*
 * Copyright (c) 2018 - Arcade Analytics LTD (https://arcadeanalytics.com)
 */

/* Generated By:JJTree: Do not edit this line. ONumber.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_USERTYPE_VISIBILITY_PUBLIC=true */
package com.arcadedb.sql.parser;

import com.arcadedb.sql.executor.Result;

import java.util.Map;

public class PNumber extends SimpleNode {
  public PNumber(int id) {
    super(id);
  }

  public PNumber(SqlParser p, int id) {
    super(p, id);
  }

  /**
   * Accept the visitor. *
   */
  public Object jjtAccept(SqlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public java.lang.Number getValue() {
    return null;
  }

  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append(value);
  }

  public PNumber copy() {
    PNumber result = new PNumber(-1);
    result.value = value;
    return result;
  }

  public Result serialize() {
    throw new UnsupportedOperationException();
  }

  public void deserialize(Result fromResult) {
    throw new UnsupportedOperationException();
  }
}
/* JavaCC - OriginalChecksum=ebedbca280f59eb8ba8f21dc6132ba10 (do not edit this line) */
