/*
 * Copyright (c) 2018 - Arcade Analytics LTD (https://arcadeanalytics.com)
 */

/* Generated By:JJTree: Do not edit this line. OSelectWithoutTargetStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_USERTYPE_VISIBILITY_PUBLIC=true */
package com.arcadedb.sql.parser;

public class SelectWithoutTargetStatement extends SelectStatement {
  public SelectWithoutTargetStatement(int id) {
    super(id);
  }

  public SelectWithoutTargetStatement(SqlParser p, int id) {
    super(p, id);
  }

  @Override public SelectStatement copy() {
    return super.copy();
  }
}
/* JavaCC - OriginalChecksum=2b0c73e32d84e559188b75251a4d262c (do not edit this line) */
