/* Generated By:JavaCC: Do not edit this line. SqlParserTreeConstants.java Version 5.0 */
package com.arcadedb.sql.parser;

public interface SqlParserTreeConstants
{
  int JJTRID = 0;
  int JJTPARSE = 1;
  int JJTPARSESCRIPT = 2;
  int JJTPSTRING = 3;
  int JJTIDENTIFIER = 4;
  int JJTPINTEGER = 5;
  int JJTFLOATINGPOINT = 6;
  int JJTPNUMBER = 7;
  int JJTSTATEMENT = 8;
  int JJTSTATEMENTSEMICOLON = 9;
  int JJTSTATEMENTINTERNAL = 10;
  int JJTQUERYSTATEMENT = 11;
  int JJTSELECTWITHOUTTARGETSTATEMENT = 12;
  int JJTSELECTSTATEMENT = 13;
  int JJTTRAVERSESTATEMENT = 14;
  int JJTMATCHSTATEMENT = 15;
  int JJTDELETESTATEMENT = 16;
  int JJTDELETEVERTEXSTATEMENT = 17;
  int JJTDELETEEDGESTATEMENT = 18;
  int JJTDELETEEDGEBYRIDSTATEMENT = 19;
  int JJTDELETEEDGEFROMTOSTATEMENT = 20;
  int JJTDELETEEDGETOSTATEMENT = 21;
  int JJTDELETEEDGEVTOSTATEMENT = 22;
  int JJTDELETEEDGEWHERESTATEMENT = 23;
  int JJTUPDATEEDGESTATEMENT = 24;
  int JJTUPDATESTATEMENT = 25;
  int JJTUPDATEOPERATIONS = 26;
  int JJTUPDATEITEM = 27;
  int JJTUPDATEINCREMENTITEM = 28;
  int JJTUPDATEREMOVEITEM = 29;
  int JJTUPDATEPUTITEM = 30;
  int JJTUPDATEADDITEM = 31;
  int JJTINSERTSTATEMENT = 32;
  int JJTINSERTBODY = 33;
  int JJTCREATEVERTEXSTATEMENTEMPTYNOTARGET = 34;
  int JJTCREATEVERTEXSTATEMENTEMPTY = 35;
  int JJTCREATEVERTEXSTATEMENT = 36;
  int JJTCREATEVERTEXSTATEMENTNOTARGET = 37;
  int JJTCREATEEDGESTATEMENT = 38;
  int JJTINPUTPARAMETER = 39;
  int JJTPOSITIONALPARAMETER = 40;
  int JJTNAMEDPARAMETER = 41;
  int JJTPROJECTION = 42;
  int JJTPROJECTIONITEM = 43;
  int JJTNESTEDPROJECTION = 44;
  int JJTNESTEDPROJECTIONITEM = 45;
  int JJTARRAYSELECTOR = 46;
  int JJTARRAYNUMBERSELECTOR = 47;
  int JJTARRAYSINGLEVALUESSELECTOR = 48;
  int JJTARRAYRANGESELECTOR = 49;
  int JJTALIAS = 50;
  int JJTRECORDATTRIBUTE = 51;
  int JJTFUNCTIONCALL = 52;
  int JJTMETHODCALL = 53;
  int JJTLEVELZEROIDENTIFIER = 54;
  int JJTSUFFIXIDENTIFIER = 55;
  int JJTBASEIDENTIFIER = 56;
  int JJTMODIFIER = 57;
  int JJTEXPRESSION = 58;
  int JJTARRAYCONCATEXPRESSION = 59;
  int JJTARRAYCONCATEXPRESSIONELEMENT = 60;
  int JJTMATHEXPRESSION = 61;
  int JJTFIRSTLEVELEXPRESSION = 62;
  int JJTPARENTHESISEXPRESSION = 63;
  int JJTBASEEXPRESSION = 64;
  int JJTFROMCLAUSE = 65;
  int JJTLETCLAUSE = 66;
  int JJTLETITEM = 67;
  int JJTFROMITEM = 68;
  int JJTBUCKET = 69;
  int JJTBUCKETLIST = 70;
  int JJTMETADATAIDENTIFIER = 71;
  int JJTINDEXNAME = 72;
  int JJTINDEXIDENTIFIER = 73;
  int JJTWHERECLAUSE = 74;
  int JJTORBLOCK = 75;
  int JJTANDBLOCK = 76;
  int JJTNOTBLOCK = 77;
  int JJTPARENTHESISBLOCK = 78;
  int JJTCONDITIONBLOCK = 79;
  int JJTCOMPAREOPERATOR = 80;
  int JJTLTOPERATOR = 81;
  int JJTGTOPERATOR = 82;
  int JJTNEOPERATOR = 83;
  int JJTNEQOPERATOR = 84;
  int JJTGEOPERATOR = 85;
  int JJTLEOPERATOR = 86;
  int JJTLIKEOPERATOR = 87;
  int JJTLUCENEOPERATOR = 88;
  int JJTNEAROPERATOR = 89;
  int JJTWITHINOPERATOR = 90;
  int JJTSCANDOPERATOR = 91;
  int JJTCONTAINSKEYOPERATOR = 92;
  int JJTCONTAINSVALUEOPERATOR = 93;
  int JJTEQUALSCOMPAREOPERATOR = 94;
  int JJTRIGHTBINARYCONDITION = 95;
  int JJTBINARYCONDITION = 96;
  int JJTCONTAINSVALUECONDITION = 97;
  int JJTINSTANCEOFCONDITION = 98;
  int JJTINDEXMATCHCONDITION = 99;
  int JJTBETWEENCONDITION = 100;
  int JJTISNULLCONDITION = 101;
  int JJTISNOTNULLCONDITION = 102;
  int JJTISDEFINEDCONDITION = 103;
  int JJTISNOTDEFINEDCONDITION = 104;
  int JJTCONTAINSCONDITION = 105;
  int JJTINOPERATOR = 106;
  int JJTINCONDITION = 107;
  int JJTNOTINCONDITION = 108;
  int JJTCONTAINSALLCONDITION = 109;
  int JJTCONTAINSANYCONDITION = 110;
  int JJTCONTAINSTEXTCONDITION = 111;
  int JJTMATCHESCONDITION = 112;
  int JJTORDERBY = 113;
  int JJTGROUPBY = 114;
  int JJTUNWIND = 115;
  int JJTLIMIT = 116;
  int JJTSKIP = 117;
  int JJTBATCH = 118;
  int JJTTIMEOUT = 119;
  int JJTWAIT = 120;
  int JJTRETRY = 121;
  int JJTPCOLLECTION = 122;
  int JJTFETCHPLAN = 123;
  int JJTFETCHPLANITEM = 124;
  int JJTTRAVERSEPROJECTIONITEM = 125;
  int JJTJSON = 126;
  int JJTMATCHEXPRESSION = 127;
  int JJTMATCHPATHITEM = 128;
  int JJTMATCHPATHITEMFIRST = 129;
  int JJTMULTIMATCHPATHITEM = 130;
  int JJTMULTIMATCHPATHITEMARROWS = 131;
  int JJTMATCHFILTER = 132;
  int JJTMATCHFILTERITEM = 133;
  int JJTOUTPATHITEM = 134;
  int JJTINPATHITEM = 135;
  int JJTBOTHPATHITEM = 136;
  int JJTOUTPATHITEMOPT = 137;
  int JJTINPATHITEMOPT = 138;
  int JJTBOTHPATHITEMOPT = 139;
  int JJTTRUNCATETYPESTATEMENT = 140;
  int JJTTRUNCATEBUCKETSTATEMENT = 141;
  int JJTTRUNCATERECORDSTATEMENT = 142;
  int JJTCREATETYPESTATEMENT = 143;
  int JJTALTERTYPESTATEMENT = 144;
  int JJTDROPTYPESTATEMENT = 145;
  int JJTIFNOTEXISTS = 146;
  int JJTCREATEPROPERTYSTATEMENT = 147;
  int JJTCREATEPROPERTYATTRIBUTESTATEMENT = 148;
  int JJTALTERPROPERTYSTATEMENT = 149;
  int JJTDROPPROPERTYSTATEMENT = 150;
  int JJTCREATEINDEXSTATEMENT = 151;
  int JJTREBUILDINDEXSTATEMENT = 152;
  int JJTDROPINDEXSTATEMENT = 153;
  int JJTCREATEBUCKETSTATEMENT = 154;
  int JJTALTERBUCKETSTATEMENT = 155;
  int JJTDROPBUCKETSTATEMENT = 156;
  int JJTALTERDATABASESTATEMENT = 157;
  int JJTCOMMANDLINEOPTION = 158;
  int JJTEXPLAINSTATEMENT = 159;
  int JJTPROFILESTATEMENT = 160;
  int JJTLETSTATEMENT = 161;
  int JJTBEGINSTATEMENT = 162;
  int JJTCOMMITSTATEMENT = 163;
  int JJTROLLBACKSTATEMENT = 164;
  int JJTRETURNSTATEMENT = 165;
  int JJTIFSTATEMENT = 166;
  int JJTSLEEPSTATEMENT = 167;


  String[] jjtNodeName = {
    "Rid",
    "parse",
    "parseScript",
    "PString",
    "Identifier",
    "PInteger",
    "FloatingPoint",
    "PNumber",
    "Statement",
    "StatementSemicolon",
    "StatementInternal",
    "QueryStatement",
    "SelectWithoutTargetStatement",
    "SelectStatement",
    "TraverseStatement",
    "MatchStatement",
    "DeleteStatement",
    "DeleteVertexStatement",
    "DeleteEdgeStatement",
    "DeleteEdgeByRidStatement",
    "DeleteEdgeFromToStatement",
    "DeleteEdgeToStatement",
    "DeleteEdgeVToStatement",
    "DeleteEdgeWhereStatement",
    "UpdateEdgeStatement",
    "UpdateStatement",
    "UpdateOperations",
    "UpdateItem",
    "UpdateIncrementItem",
    "UpdateRemoveItem",
    "UpdatePutItem",
    "UpdateAddItem",
    "InsertStatement",
    "InsertBody",
    "CreateVertexStatementEmptyNoTarget",
    "CreateVertexStatementEmpty",
    "CreateVertexStatement",
    "CreateVertexStatementNoTarget",
    "CreateEdgeStatement",
    "InputParameter",
    "PositionalParameter",
    "NamedParameter",
    "Projection",
    "ProjectionItem",
    "NestedProjection",
    "NestedProjectionItem",
    "ArraySelector",
    "ArrayNumberSelector",
    "ArraySingleValuesSelector",
    "ArrayRangeSelector",
    "Alias",
    "RecordAttribute",
    "FunctionCall",
    "MethodCall",
    "LevelZeroIdentifier",
    "SuffixIdentifier",
    "BaseIdentifier",
    "Modifier",
    "Expression",
    "ArrayConcatExpression",
    "ArrayConcatExpressionElement",
    "MathExpression",
    "FirstLevelExpression",
    "ParenthesisExpression",
    "BaseExpression",
    "FromClause",
    "LetClause",
    "LetItem",
    "FromItem",
    "Bucket",
    "BucketList",
    "MetadataIdentifier",
    "IndexName",
    "IndexIdentifier",
    "WhereClause",
    "OrBlock",
    "AndBlock",
    "NotBlock",
    "ParenthesisBlock",
    "ConditionBlock",
    "CompareOperator",
    "LtOperator",
    "GtOperator",
    "NeOperator",
    "NeqOperator",
    "GeOperator",
    "LeOperator",
    "LikeOperator",
    "LuceneOperator",
    "NearOperator",
    "WithinOperator",
    "ScAndOperator",
    "ContainsKeyOperator",
    "ContainsValueOperator",
    "EqualsCompareOperator",
    "RightBinaryCondition",
    "BinaryCondition",
    "ContainsValueCondition",
    "InstanceofCondition",
    "IndexMatchCondition",
    "BetweenCondition",
    "IsNullCondition",
    "IsNotNullCondition",
    "IsDefinedCondition",
    "IsNotDefinedCondition",
    "ContainsCondition",
    "InOperator",
    "InCondition",
    "NotInCondition",
    "ContainsAllCondition",
    "ContainsAnyCondition",
    "ContainsTextCondition",
    "MatchesCondition",
    "OrderBy",
    "GroupBy",
    "Unwind",
    "Limit",
    "Skip",
    "Batch",
    "Timeout",
    "Wait",
    "Retry",
    "PCollection",
    "FetchPlan",
    "FetchPlanItem",
    "TraverseProjectionItem",
    "Json",
    "MatchExpression",
    "MatchPathItem",
    "MatchPathItemFirst",
    "MultiMatchPathItem",
    "MultiMatchPathItemArrows",
    "MatchFilter",
    "MatchFilterItem",
    "OutPathItem",
    "InPathItem",
    "BothPathItem",
    "OutPathItemOpt",
    "InPathItemOpt",
    "BothPathItemOpt",
    "TruncateTypeStatement",
    "TruncateBucketStatement",
    "TruncateRecordStatement",
    "CreateTypeStatement",
    "AlterTypeStatement",
    "DropTypeStatement",
    "IfNotExists",
    "CreatePropertyStatement",
    "CreatePropertyAttributeStatement",
    "AlterPropertyStatement",
    "DropPropertyStatement",
    "CreateIndexStatement",
    "RebuildIndexStatement",
    "DropIndexStatement",
    "CreateBucketStatement",
    "AlterBucketStatement",
    "DropBucketStatement",
    "AlterDatabaseStatement",
    "CommandLineOption",
    "ExplainStatement",
    "ProfileStatement",
    "LetStatement",
    "BeginStatement",
    "CommitStatement",
    "RollbackStatement",
    "ReturnStatement",
    "IfStatement",
    "SleepStatement",
  };
}
/* JavaCC - OriginalChecksum=f68f86dc72725751d73efca564872c62 (do not edit this line) */
