/* Generated By:JavaCC: Do not edit this line. SqlParserTreeConstants.java Version 5.0 */
package com.arcadedb.sql.parser;

public interface SqlParserTreeConstants
{
  public int JJTRID = 0;
  public int JJTPARSE = 1;
  public int JJTPARSESCRIPT = 2;
  public int JJTPSTRING = 3;
  public int JJTIDENTIFIER = 4;
  public int JJTPINTEGER = 5;
  public int JJTFLOATINGPOINT = 6;
  public int JJTPNUMBER = 7;
  public int JJTSTATEMENT = 8;
  public int JJTSTATEMENTSEMICOLON = 9;
  public int JJTSTATEMENTINTERNAL = 10;
  public int JJTQUERYSTATEMENT = 11;
  public int JJTSELECTWITHOUTTARGETSTATEMENT = 12;
  public int JJTSELECTSTATEMENT = 13;
  public int JJTTRAVERSESTATEMENT = 14;
  public int JJTMATCHSTATEMENT = 15;
  public int JJTDELETESTATEMENT = 16;
  public int JJTDELETEVERTEXSTATEMENT = 17;
  public int JJTDELETEEDGESTATEMENT = 18;
  public int JJTDELETEEDGEBYRIDSTATEMENT = 19;
  public int JJTDELETEEDGEFROMTOSTATEMENT = 20;
  public int JJTDELETEEDGETOSTATEMENT = 21;
  public int JJTDELETEEDGEVTOSTATEMENT = 22;
  public int JJTDELETEEDGEWHERESTATEMENT = 23;
  public int JJTUPDATEEDGESTATEMENT = 24;
  public int JJTUPDATESTATEMENT = 25;
  public int JJTUPDATEOPERATIONS = 26;
  public int JJTUPDATEITEM = 27;
  public int JJTUPDATEINCREMENTITEM = 28;
  public int JJTUPDATEREMOVEITEM = 29;
  public int JJTUPDATEPUTITEM = 30;
  public int JJTUPDATEADDITEM = 31;
  public int JJTINSERTSTATEMENT = 32;
  public int JJTINSERTBODY = 33;
  public int JJTCREATEVERTEXSTATEMENTEMPTYNOTARGET = 34;
  public int JJTCREATEVERTEXSTATEMENTEMPTY = 35;
  public int JJTCREATEVERTEXSTATEMENT = 36;
  public int JJTCREATEVERTEXSTATEMENTNOTARGET = 37;
  public int JJTCREATEEDGESTATEMENT = 38;
  public int JJTINPUTPARAMETER = 39;
  public int JJTPOSITIONALPARAMETER = 40;
  public int JJTNAMEDPARAMETER = 41;
  public int JJTPROJECTION = 42;
  public int JJTPROJECTIONITEM = 43;
  public int JJTNESTEDPROJECTION = 44;
  public int JJTNESTEDPROJECTIONITEM = 45;
  public int JJTARRAYSELECTOR = 46;
  public int JJTARRAYNUMBERSELECTOR = 47;
  public int JJTARRAYSINGLEVALUESSELECTOR = 48;
  public int JJTARRAYRANGESELECTOR = 49;
  public int JJTALIAS = 50;
  public int JJTRECORDATTRIBUTE = 51;
  public int JJTFUNCTIONCALL = 52;
  public int JJTMETHODCALL = 53;
  public int JJTLEVELZEROIDENTIFIER = 54;
  public int JJTSUFFIXIDENTIFIER = 55;
  public int JJTBASEIDENTIFIER = 56;
  public int JJTMODIFIER = 57;
  public int JJTEXPRESSION = 58;
  public int JJTARRAYCONCATEXPRESSION = 59;
  public int JJTARRAYCONCATEXPRESSIONELEMENT = 60;
  public int JJTMATHEXPRESSION = 61;
  public int JJTFIRSTLEVELEXPRESSION = 62;
  public int JJTPARENTHESISEXPRESSION = 63;
  public int JJTBASEEXPRESSION = 64;
  public int JJTFROMCLAUSE = 65;
  public int JJTLETCLAUSE = 66;
  public int JJTLETITEM = 67;
  public int JJTFROMITEM = 68;
  public int JJTCLUSTER = 69;
  public int JJTCLUSTERLIST = 70;
  public int JJTMETADATAIDENTIFIER = 71;
  public int JJTINDEXNAME = 72;
  public int JJTINDEXIDENTIFIER = 73;
  public int JJTWHERECLAUSE = 74;
  public int JJTORBLOCK = 75;
  public int JJTANDBLOCK = 76;
  public int JJTNOTBLOCK = 77;
  public int JJTPARENTHESISBLOCK = 78;
  public int JJTCONDITIONBLOCK = 79;
  public int JJTCOMPAREOPERATOR = 80;
  public int JJTLTOPERATOR = 81;
  public int JJTGTOPERATOR = 82;
  public int JJTNEOPERATOR = 83;
  public int JJTNEQOPERATOR = 84;
  public int JJTGEOPERATOR = 85;
  public int JJTLEOPERATOR = 86;
  public int JJTLIKEOPERATOR = 87;
  public int JJTLUCENEOPERATOR = 88;
  public int JJTNEAROPERATOR = 89;
  public int JJTWITHINOPERATOR = 90;
  public int JJTSCANDOPERATOR = 91;
  public int JJTCONTAINSKEYOPERATOR = 92;
  public int JJTCONTAINSVALUEOPERATOR = 93;
  public int JJTEQUALSCOMPAREOPERATOR = 94;
  public int JJTRIGHTBINARYCONDITION = 95;
  public int JJTBINARYCONDITION = 96;
  public int JJTCONTAINSVALUECONDITION = 97;
  public int JJTINSTANCEOFCONDITION = 98;
  public int JJTINDEXMATCHCONDITION = 99;
  public int JJTBETWEENCONDITION = 100;
  public int JJTISNULLCONDITION = 101;
  public int JJTISNOTNULLCONDITION = 102;
  public int JJTISDEFINEDCONDITION = 103;
  public int JJTISNOTDEFINEDCONDITION = 104;
  public int JJTCONTAINSCONDITION = 105;
  public int JJTINOPERATOR = 106;
  public int JJTINCONDITION = 107;
  public int JJTNOTINCONDITION = 108;
  public int JJTCONTAINSALLCONDITION = 109;
  public int JJTCONTAINSANYCONDITION = 110;
  public int JJTCONTAINSTEXTCONDITION = 111;
  public int JJTMATCHESCONDITION = 112;
  public int JJTORDERBY = 113;
  public int JJTGROUPBY = 114;
  public int JJTUNWIND = 115;
  public int JJTLIMIT = 116;
  public int JJTSKIP = 117;
  public int JJTBATCH = 118;
  public int JJTTIMEOUT = 119;
  public int JJTWAIT = 120;
  public int JJTRETRY = 121;
  public int JJTPCOLLECTION = 122;
  public int JJTFETCHPLAN = 123;
  public int JJTFETCHPLANITEM = 124;
  public int JJTTRAVERSEPROJECTIONITEM = 125;
  public int JJTJSON = 126;
  public int JJTMATCHEXPRESSION = 127;
  public int JJTMATCHPATHITEM = 128;
  public int JJTMATCHPATHITEMFIRST = 129;
  public int JJTMULTIMATCHPATHITEM = 130;
  public int JJTMULTIMATCHPATHITEMARROWS = 131;
  public int JJTMATCHFILTER = 132;
  public int JJTMATCHFILTERITEM = 133;
  public int JJTOUTPATHITEM = 134;
  public int JJTINPATHITEM = 135;
  public int JJTBOTHPATHITEM = 136;
  public int JJTOUTPATHITEMOPT = 137;
  public int JJTINPATHITEMOPT = 138;
  public int JJTBOTHPATHITEMOPT = 139;
  public int JJTTRUNCATECLASSSTATEMENT = 140;
  public int JJTTRUNCATECLUSTERSTATEMENT = 141;
  public int JJTTRUNCATERECORDSTATEMENT = 142;
  public int JJTCREATECLASSSTATEMENT = 143;
  public int JJTALTERCLASSSTATEMENT = 144;
  public int JJTDROPCLASSSTATEMENT = 145;
  public int JJTIFNOTEXISTS = 146;
  public int JJTCREATEPROPERTYSTATEMENT = 147;
  public int JJTCREATEPROPERTYATTRIBUTESTATEMENT = 148;
  public int JJTALTERPROPERTYSTATEMENT = 149;
  public int JJTDROPPROPERTYSTATEMENT = 150;
  public int JJTCREATEINDEXSTATEMENT = 151;
  public int JJTREBUILDINDEXSTATEMENT = 152;
  public int JJTDROPINDEXSTATEMENT = 153;
  public int JJTCREATECLUSTERSTATEMENT = 154;
  public int JJTALTERCLUSTERSTATEMENT = 155;
  public int JJTDROPCLUSTERSTATEMENT = 156;
  public int JJTALTERDATABASESTATEMENT = 157;
  public int JJTCOMMANDLINEOPTION = 158;
  public int JJTEXPLAINSTATEMENT = 159;
  public int JJTPROFILESTATEMENT = 160;
  public int JJTLETSTATEMENT = 161;
  public int JJTBEGINSTATEMENT = 162;
  public int JJTCOMMITSTATEMENT = 163;
  public int JJTROLLBACKSTATEMENT = 164;
  public int JJTRETURNSTATEMENT = 165;
  public int JJTIFSTATEMENT = 166;
  public int JJTSLEEPSTATEMENT = 167;


  public String[] jjtNodeName = {
    "Rid",
    "parse",
    "parseScript",
    "PString",
    "Identifier",
    "PInteger",
    "FloatingPoint",
    "PNumber",
    "Statement",
    "StatementSemicolon",
    "StatementInternal",
    "QueryStatement",
    "SelectWithoutTargetStatement",
    "SelectStatement",
    "TraverseStatement",
    "MatchStatement",
    "DeleteStatement",
    "DeleteVertexStatement",
    "DeleteEdgeStatement",
    "DeleteEdgeByRidStatement",
    "DeleteEdgeFromToStatement",
    "DeleteEdgeToStatement",
    "DeleteEdgeVToStatement",
    "DeleteEdgeWhereStatement",
    "UpdateEdgeStatement",
    "UpdateStatement",
    "UpdateOperations",
    "UpdateItem",
    "UpdateIncrementItem",
    "UpdateRemoveItem",
    "UpdatePutItem",
    "UpdateAddItem",
    "InsertStatement",
    "InsertBody",
    "CreateVertexStatementEmptyNoTarget",
    "CreateVertexStatementEmpty",
    "CreateVertexStatement",
    "CreateVertexStatementNoTarget",
    "CreateEdgeStatement",
    "InputParameter",
    "PositionalParameter",
    "NamedParameter",
    "Projection",
    "ProjectionItem",
    "NestedProjection",
    "NestedProjectionItem",
    "ArraySelector",
    "ArrayNumberSelector",
    "ArraySingleValuesSelector",
    "ArrayRangeSelector",
    "Alias",
    "RecordAttribute",
    "FunctionCall",
    "MethodCall",
    "LevelZeroIdentifier",
    "SuffixIdentifier",
    "BaseIdentifier",
    "Modifier",
    "Expression",
    "ArrayConcatExpression",
    "ArrayConcatExpressionElement",
    "MathExpression",
    "FirstLevelExpression",
    "ParenthesisExpression",
    "BaseExpression",
    "FromClause",
    "LetClause",
    "LetItem",
    "FromItem",
    "Cluster",
    "ClusterList",
    "MetadataIdentifier",
    "IndexName",
    "IndexIdentifier",
    "WhereClause",
    "OrBlock",
    "AndBlock",
    "NotBlock",
    "ParenthesisBlock",
    "ConditionBlock",
    "CompareOperator",
    "LtOperator",
    "GtOperator",
    "NeOperator",
    "NeqOperator",
    "GeOperator",
    "LeOperator",
    "LikeOperator",
    "LuceneOperator",
    "NearOperator",
    "WithinOperator",
    "ScAndOperator",
    "ContainsKeyOperator",
    "ContainsValueOperator",
    "EqualsCompareOperator",
    "RightBinaryCondition",
    "BinaryCondition",
    "ContainsValueCondition",
    "InstanceofCondition",
    "IndexMatchCondition",
    "BetweenCondition",
    "IsNullCondition",
    "IsNotNullCondition",
    "IsDefinedCondition",
    "IsNotDefinedCondition",
    "ContainsCondition",
    "InOperator",
    "InCondition",
    "NotInCondition",
    "ContainsAllCondition",
    "ContainsAnyCondition",
    "ContainsTextCondition",
    "MatchesCondition",
    "OrderBy",
    "GroupBy",
    "Unwind",
    "Limit",
    "Skip",
    "Batch",
    "Timeout",
    "Wait",
    "Retry",
    "PCollection",
    "FetchPlan",
    "FetchPlanItem",
    "TraverseProjectionItem",
    "Json",
    "MatchExpression",
    "MatchPathItem",
    "MatchPathItemFirst",
    "MultiMatchPathItem",
    "MultiMatchPathItemArrows",
    "MatchFilter",
    "MatchFilterItem",
    "OutPathItem",
    "InPathItem",
    "BothPathItem",
    "OutPathItemOpt",
    "InPathItemOpt",
    "BothPathItemOpt",
    "TruncateClassStatement",
    "TruncateClusterStatement",
    "TruncateRecordStatement",
    "CreateClassStatement",
    "AlterClassStatement",
    "DropClassStatement",
    "IfNotExists",
    "CreatePropertyStatement",
    "CreatePropertyAttributeStatement",
    "AlterPropertyStatement",
    "DropPropertyStatement",
    "CreateIndexStatement",
    "RebuildIndexStatement",
    "DropIndexStatement",
    "CreateClusterStatement",
    "AlterClusterStatement",
    "DropClusterStatement",
    "AlterDatabaseStatement",
    "CommandLineOption",
    "ExplainStatement",
    "ProfileStatement",
    "LetStatement",
    "BeginStatement",
    "CommitStatement",
    "RollbackStatement",
    "ReturnStatement",
    "IfStatement",
    "SleepStatement",
  };
}
/* JavaCC - OriginalChecksum=3d17de6d1435cf51492c81162557e0d6 (do not edit this line) */
