
==== Java API Reference

===== Create a new database

```
Database db = new DatabaseFactory("/databases/mydb", PaginatedFile.MODE.READ_WRITE).create();
try {
  // YOUR CODE
} finally {
  db.close();
}
```


===== Open a database

```
Database db = new DatabaseFactory("/databases/mydb", PaginatedFile.MODE.READ_WRITE).open();
try {
  // YOUR CODE
} finally {
  db.close();
}
```

===== Execute a query (idempotent)

Executes a query. Only "SQL" language is supported, but in the future multiple languages could be used.

Syntax:

```java
Resultset <db>.query( String language, String command, Object... args )
```

Where:

- `language` is the language to use. Only "SQL" is supported
- `command`  is the command to execute. If the language supports prepared statements (SQL does), you can specify parameters by using `?` for positional replacement or by name by using `:<arg-name>`
- `args`     optional variable array of parameters to execute with the query. If only one parameter is passed of type `Map<String,Object>`, then the map is used to extract the named parameters

It returns a `Resultset` object where the result can be iterated.

====== Examples

Simple query:

```java
ResultSet resultset = database.query("sql", "select from V", null);
while (resultset.hasNext()) {
  Result record = resultset.next();
  System.out.println( "Found record, name = " + record.getProperty("name"));
}
```

Query passing positional parameters:

```java
ResultSet resultset = database.query("sql", "select from V where age > ? and city = ?", 18, "Melbourne");
while (resultset.hasNext()) {
  Result record = resultset.next();
  System.out.println( "Found record, name = " + record.getProperty("name"));
}
```

Query passing named parameters:

```java
Map<String,Object> parameters = new HashMap<>();
parameters.put("age", 18);
parameters.put("city", "Melbourne");

ResultSet resultset = database.query("sql", select from V where age > ? and city = ?", parameters);
while (resultset.hasNext()) {
  Result record = resultset.next();
  System.out.println( "Found record, name = " + record.getProperty("name"));
}
```


===== Execute a command (non-idempotent)

Executes a command that could change the database. This is the equivalent to `query()`, but allows the command to modify the database. Only "SQL" language is supported, but in the future multiple languages could be used.

Syntax:

```java
Resultset <db>.command( String language, String command, Object... args )
```

Where:

- `language` is the language to use. Only "SQL" is supported
- `command`  is the command to execute. If the language supports prepared statements (SQL does), you can specify parameters by using `?` for positional replacement or by name by using `:<arg-name>`
- `args`     optional variable array of parameters to execute with the query. If only one parameter is passed of type `Map<String,Object>`, then the map is used to extract the named parameters


It returns a `Resultset` object where the result can be iterated.

====== Examples

Create a new record:

```java
database.command("sql", insert into V set name = 'Jay', surname = 'Miner'", null);
```


==== Asynchronous API

The Asynchronous API schedule the operation to be executed as soon as possible, but by a different thread. ArcadeDB optimizes the usage of asynchronous threads to be equals to the number of cores found in the machine (but it is still configurable). Use Asynchronous API if the response of the operation can be managed in asynchronous way.

===== Execute a SQL query (idempotent)

```java
Database database = new DatabaseFactory("/databases/mydb", PaginatedFile.MODE.READ_WRITE).open();
try {
  database.asynch().query("sql", "select from V", null, null, new SQLCallback() {
    @Override
    public void onOk(ResultSet resultset) {
      while (resultset.hasNext()) {
        Result record = resultset.next();
        System.out.println( "Found record, name = " + record.getProperty("name"));
      }
    }

    @Override
      public void onError(Exception exception) {
      System.err.println("Error on executing the query: " + exception );
    }
  });

} finally {
  database.close();
}
```

===== Execute a SQL command (non idempotent)

```java
Database database = new DatabaseFactory("/databases/mydb", PaginatedFile.MODE.READ_WRITE).open();
try {
  database.asynch().command("sql", "insert into V set name = 'Jay', surname = 'Miner'", null, new SQLCallback() {
		@Override
		public void onOk(ResultSet resultset) {
			System.out.println("Created new record: " + resultset.next() );
		}

		@Override
		public void onError(Exception exception) {
			System.err.println("Error on creating new record: " + exception );
		}
	});

} finally {
  database.close();
}
```
