=== Java API

NOTE: ArcadeDB works in both synchronous and asynchronous mode. By using the asynchronous API you let to ArcadeDB to use all the resources of your hw/sw configuration.

==== Synchronous API

The Synchronous API execute the operation immediately and returns when it's finished. If you use a procedural approach, using the synchronous API is the easiest way to use ArcadeDB. In order to use all the resource of your machine, you need to work with multiple threads.

===== Execute a SQL query (idempotent)

```
Database database = new DatabaseFactory("/databases/mydb", PaginatedFile.MODE.READ_WRITE).open();
try {
  final ResultSet resultset = database.query("select from V", null);
  while (resultset.hasNext()) {
    Result record = resultset.next();
    System.out.println( "Found record, name = " + record.getProperty("name"));
  }
} finally {
  database.close();
}
```

===== Execute a SQL command (non idempotent)

```
Database database = new DatabaseFactory("/databases/mydb", PaginatedFile.MODE.READ_WRITE).open();
try {
  database.sql("insert into V set name = 'Jay', surname = 'Miner'", null);
} finally {
  database.close();
}
```


==== Asynchronous API

The Asynchronous API schedule the operation to be executed as soon as possible, but by a different thread. ArcadeDB optimizes the usage of asynchronous threads to be equals to the number of cores found in the machine (but it is still configurable). Use Asynchronous API if the response of the operation can be managed in asynchronous way.

===== Execute a SQL query (idempotent)

```
Database database = new DatabaseFactory("/databases/mydb", PaginatedFile.MODE.READ_WRITE).open();
try {
  database.asynch().query("select from V", null, null, new SQLCallback() {
    @Override
    public void onOk(ResultSet resultset) {
      while (resultset.hasNext()) {
        Result record = resultset.next();
        System.out.println( "Found record, name = " + record.getProperty("name"));
      }
    }

    @Override
      public void onError(Exception exception) {
      System.err.println("Error on executing the query: " + exception );
    }
  });

} finally {
  database.close();
}
```

===== Execute a SQL command (non idempotent)

```
Database database = new DatabaseFactory("/databases/mydb", PaginatedFile.MODE.READ_WRITE).open();
try {
  database.asynch().sql("insert into V set name = 'Jay', surname = 'Miner'", null, new SQLCallback() {
		@Override
		public void onOk(ResultSet resultset) {
			System.out.println("Created new record: " + resultset.next() );
		}

		@Override
		public void onError(Exception exception) {
			System.err.println("Error on creating new record: " + exception );
		}
	});

} finally {
  database.close();
}
```
