/* Generated By:JJTree: Do not edit this line. OFromClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.arcadedb.sql.parser;

import com.arcadedb.sql.executor.OResult;
import com.arcadedb.sql.executor.OResultInternal;

import java.util.Map;

public class FromClause extends SimpleNode {

  FromItem item;

  public FromClause(int id) {
    super(id);
  }

  public FromClause(SqlParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SqlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (item != null) {
      item.toString(params, builder);
    }
  }


  public FromItem getItem() {
    return item;
  }

  public void setItem(FromItem item) {
    this.item = item;
  }

  public FromClause copy() {
    FromClause result= new FromClause(-1);
    result.item = item.copy();
    return result;
  }

  @Override public boolean equals(Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;

    FromClause that = (FromClause) o;

    if (item != null ? !item.equals(that.item) : that.item != null)
      return false;

    return true;
  }

  @Override public int hashCode() {
    return item != null ? item.hashCode() : 0;
  }

  public OResult serialize() {
    OResultInternal result = new OResultInternal();
    result.setProperty("item", item.serialize());
    return result;
  }

  public void deserialize(OResult fromResult) {
    item = new FromItem(-1);
    item.deserialize(fromResult.getProperty("item"));
  }

  public boolean isCacheable() {
    return item.isCacheable();
  }
}
/* JavaCC - OriginalChecksum=051839d20dabfa4cce26ebcbe0d03a86 (do not edit this line) */
