/* Generated By:JJTree: Do not edit this line. ONeqOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.arcadedb.sql.parser;

import com.arcadedb.sql.executor.OQueryOperatorEquals;

public class NeqOperator extends SimpleNode implements BinaryCompareOperator {
  public NeqOperator(int id) {
    super(id);
  }

  public NeqOperator(SqlParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SqlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  @Override
  public boolean execute(Object left, Object right) {
    return !OQueryOperatorEquals.equals(left, right);
  }

  @Override
  public String toString() {
    return "<>";
  }

  @Override public boolean supportsBasicCalculation() {
    return true;
  }

  @Override public NeqOperator copy() {
    return this;
  }

  @Override public boolean equals(Object obj) {
    return obj != null && obj.getClass().equals(this.getClass());
  }

  @Override public int hashCode() {
    return getClass().hashCode();
  }
}
/* JavaCC - OriginalChecksum=588c4112ae7d2c83239f97ab0d2d5989 (do not edit this line) */
