/* Generated By:JJTree&JavaCC: Do not edit this line. OrientSql.java */
package com.arcadedb.sql.parser;

import java.io.InputStream;
import java.io.UnsupportedEncodingException;

/**
 * Orient Database Sql grammar.
 */
public class OrientSql/*@bgen(jjtree)*/ implements OrientSqlTreeConstants, OrientSqlConstants {/*@bgen(jjtree)*/
  protected JJTOrientSqlState jjtree          = new JJTOrientSqlState();
  private   int               inputParamCount = 0;

  public OrientSql(InputStream is) {

  }

  public OrientSql(InputStream is, String s) throws UnsupportedEncodingException, ParseException {

  }

  public OStatement parse() {
    return null;
  }
}
