/* Generated By:JJTree: Do not edit this line. ORid.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.arcadedb.sql.parser;

import com.arcadedb.database.PIdentifiable;
import com.arcadedb.database.PRID;
import com.arcadedb.sql.executor.OBasicCommandContext;
import com.arcadedb.sql.executor.OCommandContext;
import com.arcadedb.sql.executor.OResult;
import com.arcadedb.sql.executor.OResultInternal;

import java.util.Map;

public class Rid extends SimpleNode {
  protected PInteger cluster;
  protected PInteger position;

  protected Expression expression;
  protected boolean    legacy;

  public Rid(int id) {
    super(id);
  }

  public Rid(OrientSql p, int id) {
    super(p, id);
  }

  /**
   * Accept the visitor.
   **/
  public Object jjtAccept(OrientSqlVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  @Override
  public String toString(String prefix) {
    return "#" + cluster.getValue() + ":" + position.getValue();
  }

  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (legacy) {
      builder.append("#" + cluster.getValue() + ":" + position.getValue());
    } else {
      builder.append("{\"@rid\":");
      expression.toString(params, builder);
      builder.append("}");
    }
  }

  public PRID toRecordId(OResult target, OCommandContext ctx) {
    if (legacy) {
      return new PRID(ctx.getDatabase(), cluster.value.intValue(), position.value.longValue());
    } else {
      Object result = expression.execute(target, ctx);
      if (result == null) {
        return null;
      }
      if (result instanceof PIdentifiable) {
        return ((PIdentifiable) result).getIdentity();
      }
      if (result instanceof String) {
        throw new UnsupportedOperationException();
      }
      return null;
    }
  }

  public PRID toRecordId(PIdentifiable target, OCommandContext ctx) {
    if (legacy) {
      return new PRID(ctx.getDatabase(), cluster.value.intValue(), position.value.longValue());
    } else {
      Object result = expression.execute(target, ctx);
      if (result == null) {
        return null;
      }
      if (result instanceof PIdentifiable) {
        return ((PIdentifiable) result).getIdentity();
      }
      if (result instanceof String) {
        throw new UnsupportedOperationException();
      }
      return null;
    }
  }

  public Rid copy() {
    Rid result = new Rid(-1);
    result.cluster = cluster == null ? null : cluster.copy();
    result.position = position == null ? null : position.copy();
    result.expression = expression == null ? null : expression.copy();
    result.legacy = legacy;
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;

    Rid oRid = (Rid) o;

    if (cluster != null ? !cluster.equals(oRid.cluster) : oRid.cluster != null)
      return false;
    if (position != null ? !position.equals(oRid.position) : oRid.position != null)
      return false;
    if (expression != null ? !expression.equals(oRid.expression) : oRid.expression != null)
      return false;
    if (legacy != oRid.legacy)
      return false;

    return true;
  }

  @Override
  public int hashCode() {
    int result = cluster != null ? cluster.hashCode() : 0;
    result = 31 * result + (position != null ? position.hashCode() : 0);
    result = 31 * result + (expression != null ? expression.hashCode() : 0);
    return result;
  }

  public void setCluster(PInteger cluster) {
    this.cluster = cluster;
  }

  public void setPosition(PInteger position) {
    this.position = position;
  }

  public void setLegacy(boolean b) {
    this.legacy = b;
  }

  public PInteger getCluster() {
    if (expression != null) {
      PRID rid = toRecordId((OResult) null, new OBasicCommandContext());
      if (rid == null) {
        PInteger result = new PInteger(-1);
        result.setValue(rid.getBucketId());
        return result;
      }
    }
    return cluster;
  }

  public PInteger getPosition() {
    if (expression != null) {
      PRID rid = toRecordId((OResult) null, new OBasicCommandContext());
      if (rid == null) {
        PInteger result = new PInteger(-1);
        result.setValue(rid.getPosition());
        return result;
      }
    }
    return position;
  }

  public OResult serialize() {
    OResultInternal result = new OResultInternal();
    if(cluster!=null){
      result.setProperty("cluster", cluster.serialize());
    }
    if(position!=null){
      result.setProperty("position", position.serialize());
    }
    if(expression!=null){
      result.setProperty("expression", expression.serialize());
    }
    result.setProperty("legacy", legacy);
    return result;
  }

  public void deserialize(OResult fromResult) {
    if(fromResult.getProperty("cluster")!=null){
      cluster = new PInteger(-1);
      cluster.deserialize(fromResult.getProperty("cluster"));
    }
    if(fromResult.getProperty("position")!=null){
      position = new PInteger(-1);
      position.deserialize(fromResult.getProperty("position"));
    }
    if(fromResult.getProperty("expression")!=null){
      expression = new Expression(-1);
      expression.deserialize(fromResult.getProperty("expression"));
    }
    legacy = fromResult.getProperty("legacy");
  }
}
/* JavaCC - OriginalChecksum=c2c6d67d7722e29212e438574698d7cd (do not edit this line) */
